spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/github-tags-db
    username: postgres
    password: postgres
hibernate:
  dialect: org.hibernate.dialect.PostgreSQL13Dialect