spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/github-tags-db
    username: postgres
    password: postgres
server:
  error:
    include-message: always
com:
  tags-server:
    github:
      client-id: b34d2a6fc9da4d853f0a # Your Client ID Here
      client-secret: bf7914d3bce7e9a5cb6ec9eb9126cc6eeafc8bc3 # Your Secret Here
      user-base-url: https://api.github.com/user