spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
server:
  error:
    include-message: always
com:
  tags-server:
    github:
      user-base-url: https://api.github.com/user